name: bhg_marburg
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2022.9.24
  - libcxx=14.0.6
  - libffi=3.2.1
  - libsqlite=3.40.0
  - libzlib=1.2.13
  - ncurses=6.3
  - openssl=1.1.1s
  - pip=22.3.1
  - python=3.8.0
  - readline=8.1.2
  - setuptools=65.5.1
  - sqlite=3.40.0
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.2.6
  - zlib=1.2.13
  - pip:
    - aiohttp==3.8.3
    - aiosignal==1.3.1
    - anyio==3.6.2
    - appnope==0.1.3
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.1.0
    - async-timeout==4.0.2
    - attrs==22.1.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - bokeh==2.4.3
    - certifi==2022.9.24
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - colorcet==3.0.1
    - contourpy==1.0.6
    - cycler==0.11.0
    - cython==0.29.32
    - debugpy==1.6.3
    - decorator==5.1.1
    - defusedxml==0.7.1
    - entrypoints==0.4
    - executing==1.2.0
    - fastjsonschema==2.16.2
    - fonttools==4.38.0
    - frozenlist==1.3.3
    - holoviews==1.15.2
    - idna==3.4
    - imageio==2.22.4
    - importlib-metadata==5.1.0
    - importlib-resources==5.10.0
    - ipykernel==6.17.1
    - ipython==8.6.0
    - ipython-genutils==0.2.0
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonschema==4.17.1
    - jupyter-client==7.4.7
    - jupyter-contrib-core==0.4.2
    - jupyter-contrib-nbextensions==0.7.0
    - jupyter-core==5.0.0
    - jupyter-highlight-selected-word==0.2.0
    - jupyter-nbextensions-configurator==0.6.1
    - jupyter-server==1.23.3
    - jupyterlab-pygments==0.2.2
    - kiwisolver==1.4.4
    - lazy-loader==0.1rc2
    - littleutils==0.2.2
    - lxml==4.9.1
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.6.2
    - matplotlib-inline==0.1.6
    - mistune==2.0.4
    - multidict==6.0.2
    - nbclassic==0.4.8
    - nbclient==0.7.0
    - nbconvert==7.2.5
    - nbformat==5.7.0
    - nest-asyncio==1.5.6
    - networkx==2.8.8
    - notebook==6.5.2
    - notebook-shim==0.2.2
    - numpy==1.23.5
    - outdated==0.2.2
    - packaging==21.3
    - pandas==1.5.2
    - pandas-flavor==0.3.0
    - pandocfilters==1.5.0
    - panel==0.14.1
    - param==1.12.2
    - parso==0.8.3
    - patsy==0.5.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.3.0
    - pingouin==0.5.2
    - pkgutil-resolve-name==1.3.10
    - platformdirs==2.5.4
    - plotly==5.11.0
    - prometheus-client==0.15.0
    - prompt-toolkit==3.0.33
    - psutil==5.9.4
    - ptitprince==0.2.6
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pycparser==2.21
    - pyct==0.4.8
    - pygments==2.13.0
    - pyhamcrest==2.0.4
    - pyparsing==3.0.9
    - pyrsistent==0.19.2
    - python-dateutil==2.8.2
    - pytz==2022.6
    - pyviz-comms==2.2.1
    - pywavelets==1.4.1
    - pyyaml==6.0
    - pyzmq==24.0.1
    - requests==2.28.1
    - rise==5.7.1
    - scikit-image==0.19.3
    - scikit-learn==1.0.2
    - scipy==1.9.3
    - seaborn==0.11.0
    - send2trash==1.8.0
    - six==1.16.0
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - stack-data==0.6.1
    - statsmodels==0.13.5
    - tabulate==0.9.0
    - tenacity==8.1.0
    - terminado==0.17.0
    - threadpoolctl==3.1.0
    - tifffile==2022.10.10
    - tinycss2==1.2.1
    - tornado==6.2
    - tqdm==4.64.1
    - traitlets==5.5.0
    - traits==6.4.1
    - typing-extensions==4.4.0
    - urllib3==1.26.13
    - vtk==9.2.2
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.4.2
    - wslink==1.9.1
    - xarray==2022.11.0
    - yarl==1.8.1
    - zipp==3.10.0
